### ISSUE TITLE
Write unit test for parsing `example-config.toml`

### ISSUE THREAD

**Issue by chshersh** [kowainik/crocodealer#10]
We have a codec for TOML configuration and an example configuration. Let's also implement a simple unit test for the file to make sure that the codec works as expected.

**Comment by mstruebing** [comment]
I would love to try that in order to boost my haskell knowledge :)

**Comment by chshersh** [comment]
@mstruebing Sure, go ahead! Feel free to ask any questions :slightly_smiling_face:

**Comment by vrom911** [comment]
Resolved in #11
